name: Lua Lint

on:
  push:
    branches:
    - master
    paths:
      - "lua/**"
      - "init.lua"
      - ".github/workflows/lint.yml"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Tools
      env:
        SELENE_VERSION: '0.17.0'
        STYLUA_VERSION: 'v0.14.0'
      run: |
        wget -c "https://github.com/Kampfkarren/selene/releases/download/$SELENE_VERSION/selene-$SELENE_VERSION-linux.zip" -O ./selene.zip
        unzip ./selene.zip
        chmod +x ./selene
        wget -c "https://github.com/JohnnyMorganz/StyLua/releases/download/$STYLUA_VERSION/stylua-linux.zip" -O ./stylua.zip
        unzip ./stylua.zip
        chmod +x ./stylua
    - name: Run lint
      shell: bash
      run: |
        export PATH=$PWD:$PATH
        ./asset/scripts/check.sh
